version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: livestore-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: livestore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - livestore-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./apps/server
    container_name: livestore-fastapi
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/livestore
      AUTH_TOKEN: ${AUTH_TOKEN:-insecure-token-change-me}
      ADMIN_SECRET: ${ADMIN_SECRET:-change-me-admin-secret}
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - livestore-network
    volumes:
      - ./apps/server/app:/app/app # For development hot-reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  livestore-network:
    driver: bridge

volumes:
  postgres_data:
